@username=smith
@password=123456

POST http://localhost:4200/api/auth/signup
content-type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

###

POST http://localhost:4200/api/auth/signin
content-type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

###

http://localhost:4200/api/insurance-policy

###

POST http://localhost:4200/api/insurance-policy
content-type: application/json

{
    "policyId": "9875321",
    "type": "auto",
    "holder": "{{username}}",
    "premium": 5000
}

###

@policy_db_id=65ca9230795cee6fffbfda48

###
http://localhost:4200/api/insurance-policy/{{policy_db_id}}

###

PUT http://localhost:4200/api/insurance-policy/{{policy_db_id}}
content-type: application/json

{
    "policyId": "9875321",
    "type": "car",
    "holder": "{{username}}",
    "premium": 15000
}

###

DELETE http://localhost:4200/api/insurance-policy/{{policy_db_id}}
